services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BLOG_DB_HOST=mariadb
      - BLOG_DB_NAME=blog_db
      - BLOG_DB_USER=${BLOG_DB_USER}
      - BLOG_DB_PASSWORD=${BLOG_DB_PASSWORD}
      - BLOG_BACKEND_API_KEY=${BLOG_BACKEND_API_KEY}
      - BLOG_BACKEND_JWT_SECRET=${BLOG_BACKEND_JWT_SECRET}
      - BLOG_BACKEND_PORT=${BLOG_BACKEND_PORT}
    restart: unless-stopped

    networks:
      - database
      - backend

    depends_on:
      - mariadb


  mariadb:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=${BLOG_DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=blog_db
      - MARIADB_USER=${BLOG_DB_USER}
      - MARIADB_PASSWORD=${BLOG_DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - database

networks:
  backend:
    external: false
  database:
    external: false
volumes:
  mariadb_data:
